### ISSUE TITLE
Mobile layout is broken

### ISSUE THREAD

**Issue by atomiccupcake** [woogles-io/liwords#1229]
pixel 8 pro

![Screenshot_20231119-162137](https://github.com/domino14/liwords/assets/6097979/e91e1533-18d0-487b-bf3b-9466ea090e44) 

iphone11 safari 
![received_1088870412470583~2](https://github.com/domino14/liwords/assets/6097979/89e7224c-376c-45a8-8f17-023e897ed08e)

You can replicate on desktop by narrowing your window. Seen in Android Chrome, Mac Chrome, and Mac Firefox, ios safari 

Board no longer zooms out below 522 pixels wide. The header is no longer full width and the rest of the page shows on scroll. Buttons are no longer centered. This is likely completely hiding the edge columns of the board on smaller devices.

**Comment by domino14** [comment]
is this still the case?

**Comment by atomiccupcake** [comment]
Looks good now!
