### ISSUE TITLE
Add new CSW21/CSW24 leaves when available

### ISSUE THREAD

**Issue by domino14** [woogles-io/liwords#1376]
Using @jvc56's crazy generational leaves

**Comment by jvc56** [comment]
CSW21 klv2 leaves are available here: https://drive.google.com/drive/u/0/folders/10Sqi4rmDB3IWibSyWIuvzXfupapBfI6I and John O'Laughlin is working on CSW24 values right now!

**Comment by domino14** [comment]
most recent leaves are from magpie.
