### ISSUE TITLE
Got nudged as observer of a game

### ISSUE THREAD

**Issue by magratheazaphod** [woogles-io/liwords#823]
Not 100% sure that this is a bug - I was observing [this game](https://woogles.io/game/mXNaqZzC) just now, and got a notification that I'd been "nudged." I suspect it was intended for a player in the game.

**Comment by domino14** [comment]
:O

**Comment by domino14** [comment]
Apparently if a watcher answers these nudges, it actually acts as if the nudgee answered it! 🤦🏼

**Comment by domino14** [comment]
Unable to reproduce this anymore. We might have fixed it.

**Comment by domino14** [comment]
still being reported and reproducible; will need to handle

**Comment by domino14** [comment]
```
3 browsers (eg chrome safari firefox)
browser 1 as A playing vs B
browser 2 as B playing the same game vs A
browser 3 as anonymous (you don't have to be logged in)
you just start watching the game (or refresh if you're already in it -- the popup only shows on load) and you'll be able to anonymously accept the abort request or click keep playing, nobody's going to be any wiser
```
